version: "3"
services:
    lint:
        image: namely/protoc-all:1.16_0
        volumes:
            - .:/defs
        entrypoint: "sh -c"
        command: '"protoc -I/usr/local/include -I. --lint_out=. ./*/protos/*.proto"'
    go:
        image: namely/protoc-all:1.16_0
        volumes:
            - .:/defs
        command: "-d ./${PROJECT}/protos -o ./${PROJECT}/pb-go --with-docs markdown,readme.md --with-gateway -l go"
    java:
        image: namely/protoc-all:1.16_0
        volumes:
            - .:/defs
        command: "-d ./${PROJECT}/protos -o ./${PROJECT}/pb-java --with-docs markdown,readme.md -l java"
