// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserCreationRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string   `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreationRequest) Reset()         { *m = UserCreationRequest{} }
func (m *UserCreationRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreationRequest) ProtoMessage()    {}
func (*UserCreationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserCreationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreationRequest.Unmarshal(m, b)
}
func (m *UserCreationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreationRequest.Marshal(b, m, deterministic)
}
func (m *UserCreationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreationRequest.Merge(m, src)
}
func (m *UserCreationRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreationRequest.Size(m)
}
func (m *UserCreationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreationRequest proto.InternalMessageInfo

func (m *UserCreationRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserCreationRequest) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserCreationRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserSearchRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserSearchRequest) Reset()         { *m = UserSearchRequest{} }
func (m *UserSearchRequest) String() string { return proto.CompactTextString(m) }
func (*UserSearchRequest) ProtoMessage()    {}
func (*UserSearchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserSearchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserSearchRequest.Unmarshal(m, b)
}
func (m *UserSearchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserSearchRequest.Marshal(b, m, deterministic)
}
func (m *UserSearchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserSearchRequest.Merge(m, src)
}
func (m *UserSearchRequest) XXX_Size() int {
	return xxx_messageInfo_UserSearchRequest.Size(m)
}
func (m *UserSearchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserSearchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserSearchRequest proto.InternalMessageInfo

func (m *UserSearchRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type UserResponse struct {
	UserId               uint64               `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Email                string               `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Nickname             string               `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Password             string               `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUserId() uint64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserResponse) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *UserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserResponse) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *UserResponse) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func init() {
	proto.RegisterType((*UserCreationRequest)(nil), "UserCreationRequest")
	proto.RegisterType((*UserSearchRequest)(nil), "UserSearchRequest")
	proto.RegisterType((*UserResponse)(nil), "UserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x3d, 0x4e, 0x03, 0x31,
	0x14, 0x84, 0xb5, 0xf9, 0x83, 0xbc, 0x00, 0x52, 0x9c, 0x48, 0x84, 0x15, 0x12, 0x68, 0x2b, 0xa0,
	0xf0, 0x8a, 0x50, 0x41, 0x87, 0x28, 0x10, 0x94, 0x0b, 0xd4, 0x91, 0xb3, 0xfb, 0x08, 0x16, 0x59,
	0x7b, 0xb1, 0x9d, 0x50, 0x20, 0x1a, 0xae, 0xc0, 0x0d, 0x38, 0x01, 0x77, 0xe1, 0x0a, 0x1c, 0x04,
	0xd9, 0xce, 0x46, 0xe1, 0x2f, 0xe5, 0x78, 0x46, 0xf3, 0xfc, 0x0d, 0xc0, 0x44, 0xa3, 0xa2, 0x85,
	0x92, 0x46, 0x86, 0x3b, 0x23, 0x29, 0x47, 0x63, 0x8c, 0x9d, 0x1a, 0x4e, 0x6e, 0x63, 0xc3, 0x73,
	0xd4, 0x86, 0xe5, 0xc5, 0x2c, 0xb0, 0x3d, 0x0b, 0xb0, 0x82, 0xc7, 0x4c, 0x08, 0x69, 0x98, 0xe1,
	0x52, 0x68, 0xef, 0x46, 0x29, 0x74, 0x6e, 0x34, 0xaa, 0x33, 0x85, 0xee, 0x39, 0xc1, 0x87, 0x09,
	0x6a, 0x43, 0xba, 0x50, 0xc7, 0x9c, 0xf1, 0x71, 0x2f, 0xd8, 0x0d, 0xf6, 0x9a, 0x89, 0x17, 0x24,
	0x84, 0x55, 0xc1, 0xd3, 0x7b, 0xc1, 0x72, 0xec, 0x55, 0x9c, 0x31, 0xd7, 0xd6, 0x2b, 0x98, 0xd6,
	0x8f, 0x52, 0x65, 0xbd, 0xaa, 0xf7, 0x4a, 0x1d, 0xed, 0x43, 0xdb, 0x1e, 0xb9, 0x42, 0xa6, 0xd2,
	0xbb, 0xa5, 0x27, 0xa2, 0xf7, 0x00, 0xd6, 0x6c, 0x36, 0x41, 0x5d, 0x48, 0xa1, 0x91, 0x6c, 0xc2,
	0x8a, 0xa5, 0x1d, 0xf0, 0xcc, 0x05, 0x6b, 0x49, 0xc3, 0xca, 0x8b, 0x8c, 0x1c, 0x03, 0xa4, 0xf6,
	0xd7, 0x98, 0x0d, 0x98, 0x71, 0xdf, 0x69, 0xf5, 0x43, 0xea, 0x61, 0x69, 0xb9, 0x06, 0xbd, 0x2e,
	0xd7, 0x48, 0x9a, 0xb3, 0xf4, 0xe9, 0xc2, 0xe9, 0xea, 0x7f, 0x74, 0xb5, 0x25, 0x74, 0xf5, 0xef,
	0x74, 0xfd, 0xb7, 0x00, 0x5a, 0x1e, 0x4f, 0x4d, 0x79, 0x8a, 0xe4, 0x1c, 0xc0, 0xcd, 0x89, 0xf6,
	0x91, 0x74, 0xe9, 0x1f, 0xfb, 0x86, 0xeb, 0x74, 0x11, 0x32, 0xea, 0xbe, 0x7c, 0x7c, 0xbe, 0x56,
	0x36, 0xa2, 0x66, 0x3c, 0x3d, 0x8c, 0x2d, 0x9f, 0x3e, 0x09, 0x0e, 0xc8, 0x25, 0x80, 0x9f, 0xcc,
	0x15, 0x11, 0xfa, 0x6b, 0xc3, 0x9f, 0x35, 0x5b, 0xae, 0xa6, 0x43, 0xda, 0xf3, 0x9a, 0xf8, 0xc9,
	0xb1, 0x3d, 0x0f, 0x1b, 0x6e, 0x91, 0xa3, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0xb4, 0x48,
	0x86, 0x3b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *UserCreationRequest, opts ...grpc.CallOption) (*UserResponse, error)
	SearchUser(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *UserCreationRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) SearchUser(ctx context.Context, in *UserSearchRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/UserService/SearchUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *UserCreationRequest) (*UserResponse, error)
	SearchUser(context.Context, *UserSearchRequest) (*UserResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*UserCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_SearchUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SearchUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/SearchUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SearchUser(ctx, req.(*UserSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "SearchUser",
			Handler:    _UserService_SearchUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
